### ISSUE TITLE
how to compute the mean and std of the data

### ISSUE THREAD

**Issue by predawnang** [cyhuang-tw/attack-vc#3]
Hi, dear author

I learn a lot from this work, it's a great work. 

Currently, I‘m working on a project, I want to do normalization on my data (mel-spectrogram ) for a better training performance.

I noticed that the std and mean of the data is precomputed, would you mind to tell me how to compute the std and mean of the data. 

Thanks.

**Comment by cyhuang-tw** [comment]
Hi,

Thanks for your interest in this work.

I used the precomputed values directly from [the official implementation](https://github.com/jjery2243542/adaptive_voice_conversion) of AdaIN-VC.
I believe these values were computed from the mel-spectrograms of the training data.
