### ISSUE TITLE
Issue About Pretrained Models of AdaIN-VC 

### ISSUE THREAD

**Issue by windforestfiremountain** [cyhuang-tw/attack-vc#4]
Hello,Thanks for your code and the pretrained-model. However, the [GoogleDrive link](https://drive.google.com/file/d/1vBF-4s5u0sro3nwDFWL7VnAV6KViCMp0/view?usp=sharing) become invalid these days. Would you please update this link? Thanks you very much!

**Comment by 18383045974** [comment]
Thanks for your work, I meet the same question. Could you update the link?

**Comment by cyhuang-tw** [comment]
Sorry for the late reply. I have updated the Google Drive link.
Please feel free to contact me if you have any further questions.
